site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Hausenblas'
docs_dir: docs/
site_dir: _site/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'
nav:
    - Home: index.md
    - Test: test2.md
theme:
  name: 'material'
